---
label: Site Config
hide_body: false
display_field: title
fields:
- name: title
  label: Bloomspace
  type: text
  hidden: false
  default: ''
- name: description
  label: Description
  type: text
  hidden: false
  default: ''
- type: file
  name: logo
  label: Logo
  default: "/upload/black_logo_-_no_background.jpeg"
- name: footer
  label: Footer
  type: text
  hidden: false
  default: ''
- name: favicon
  label: Favicon
  type: file
  hidden: false
  default: ''
- name: navigation
  label: Navigation
  type: field_group_list
  fields:
  - name: text
    label: Text
    type: text
    hidden: false
    default: ''
  - name: link
    label: Link
    type: text
    hidden: false
    default: ''
  - type: select
    config:
      source:
        type: simple
      options:
      - left
      - right
    label: Position
    name: position
  - name: external
    label: External
    type: boolean
    hidden: false
    default: ''
  hidden: false
  default: ''
